### ISSUE TITLE
calculator `Morb` is not compatible with a Path

### ISSUE THREAD

**Issue by shishirkrpandey** [wannier-berri/wannier-berri#275]
Hi, 
I am trying to calculate the contribution to Morb along some high-symmetry directions with 

calculators ["tabulate"] = wberri.calculators.TabulatorAll({
                             "Energy":wberri.calculators.tabulate.Energy(),
                             "berry":wberri.calculators.tabulate.BerryCurvature(),
                             "morb":wberri.calculators.tabulate.OrbitalMoment(),
                                         },
                             ibands = np.arange(0,21))

path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000 ],   #  G
        [0.5000, 0.0000, 0.0000],   #  H
        [0.3333, 0.3333, 0.0000],   #  P
        [0.0000, 0.0000, 0.5000],   #  N
        [0.5000, 0.0000, 0.5000],
        [0.3333, 0.3333, 0.5000 ],
        [0.0000, 0.0000, 0.5000 ]] , #  G
                 labels=["G","M","K","G","A", "L", "H"],
                 length=200 )
result_run = wberri.run(system,
            grid=path,
            calculators = calculators,
            parallel=parallel,
            adpt_num_iter=5,
            fout_name='ef',
            restart=False,
            )

But the following error occurs:

   raise ValueError(f"Calculation along a Path is running, but calculator `{key}` is not compatible with a Path")
ValueError: Calculation along a Path is running, but calculator `Morb` is not compatible with a Path

However, if I run with a grid, the calculation runs fine.  Can I not use tabulate calculator with "Path" option?

Thanking you anticipating your response.

**Comment by stepan-tsirkin** [comment]
Hi, 

1. the `TabulatorAll` should be in a `"path"` mode, i.e. `TabulatorAll(..., mode="path",...)`
https://docs.wannier-berri.org/en/master/docs/calculators.html#wannierberri.calculators.TabulatorAll
2. `"Morb"` is not in the lines that you show. Did you forget to remove it? Or did you intend to use it outside the `TabulatorAll` calculator on the path? this is not supported
3. in your case `"morb"` will give the band-by-band orbital moment. The sum of those over occupied bands will **NOT** give the k-resolved Morb
4.  `adpt_num_iter` has no effect on a path calculation
5. if you actually want to get the k-resolved contribution to Morb along the path, there needs a small modification in the code. I will let you know

**Comment by stepan-tsirkin** [comment]
@shishirkrpandey ,

I implemented the plotting of k-resolved Morb in this PR #276 

Please, try it and give feedback.

**Comment by shishirkrpandey** [comment]
Hello!!! Thank you for your prompt response yesterday. 
 I tried it but the same error persists. After updating the  `tab_static` branch which gives the version "wannierberri==0.14.1a0", I tried to run the following script after modifying the example that you provided. 

`!/usr/bin/env python3
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1' 
os.environ['MKL_NUM_THREADS'] = '1' 

## these linesline if you want to use the git version of the code, instead of the one installed by pip
local_code=False
num_proc=30
import os
if local_code:
   if 'wannierberri' not in os.listdir() :
       os.symlink("../wannierberri","wannierberri")
else:
   if 'wannierberri' in os.listdir() :
       os.remove('wannierberri')

import wannierberri as wberri
import numpy as np

SYM=wberri.symmetry
Efermi=np.linspace(7.5035, 7.5235,10)

system=wberri.System_w90(seedname='wannier90',berry=True,morb=True,spin=True, guiding_centers = True)

generators=[]
system.set_symmetry(generators)

grid=wberri.Grid(system,length=600,length_FFT=50)
parallel=wberri.Parallel(num_cpus=num_proc)

calculators = {}
noext = dict(kwargs_formula={"external_terms":False})
calculators ["tabulate"] = wberri.calculators.TabulatorAll({
                            "Energy":wberri.calculators.tabulate.Energy(),
                            "berry":wberri.calculators.tabulate.BerryCurvature(**noext),
                            "morb":wberri.calculators.tabulate.OrbitalMoment(**noext),
                            "Morb":wberri.calculators.static.Morb(Efermi=Efermi,k_resolved=True,**noext),
                                  },
                            ibands = np.arange(0,21),
                            mode="path")

path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000 ],   #  G
        [0.5000, 0.0000, 0.0000],   #  H
        [0.3333, 0.3333, 0.0000],   #  P
        [0.0000, 0.0000, 0.5000],   #  N
        [0.5000, 0.0000, 0.5000],
        [0.3333, 0.3333, 0.5000 ],
        [0.0000, 0.0000, 0.5000 ]] , #  G
                 labels=["G","M","K","G","A", "L", "H"],
                 length=200 )
result_run = wberri.run(system,
            grid=path,
            calculators = calculators,
            parallel=parallel,
            adpt_num_iter=5,
            fout_name='ef',
            restart=False,
            print_Kpoints=False
            )

open("data_Morb","w").write(result_run.results["tabulate"].results["Morb"].data) # To write data in a file since I am running a slurm job

parallel.shutdown()`

But again the same error occurs which is: 
    result_run = wberri.run(system,
  File "/public/home/skp/software/wannier-berri-tab_static/wannierberri/run.py", line 180, in run 
    raise ValueError(f"Calculation along a Path is running, but calculator `{key}` is not compatible with a Path")
ValueError: Calculation along a Path is running, but calculator `Morb` is not compatible with a Path

I would appreciate your help.

**Comment by shishirkrpandey** [comment]
Hello!!! Thank you for your prompt response yesterday. 
 I tried it but the same error persists. After updating the  `tab_static` branch (using pip install -e .), which updates the version to "wannierberri==0.14.1a0", I tried to run the following script after modifying the example that you provided. 

`!/usr/bin/env python3
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1' 
os.environ['MKL_NUM_THREADS'] = '1' 

local_code=False
num_proc=30
import os
if local_code:
   if 'wannierberri' not in os.listdir() :
       os.symlink("../wannierberri","wannierberri")
else:
   if 'wannierberri' in os.listdir() :
       os.remove('wannierberri')

import wannierberri as wberri
import numpy as np

SYM=wberri.symmetry
Efermi=np.linspace(7.5035, 7.5235,10)

system=wberri.System_w90(seedname='wannier90',berry=True,morb=True,spin=True, guiding_centers = True)

generators=[]
system.set_symmetry(generators)

grid=wberri.Grid(system,length=600,length_FFT=50)
parallel=wberri.Parallel(num_cpus=num_proc)

calculators = {}
noext = dict(kwargs_formula={"external_terms":False})
calculators ["tabulate"] = wberri.calculators.TabulatorAll({
                            "Energy":wberri.calculators.tabulate.Energy(),
                            "berry":wberri.calculators.tabulate.BerryCurvature(**noext),
                            "morb":wberri.calculators.tabulate.OrbitalMoment(**noext),
                            "Morb":wberri.calculators.static.Morb(Efermi=Efermi,k_resolved=True,**noext),
                                  },
                            ibands = np.arange(0,21),
                            mode="path")

path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000 ],   #  G
        [0.5000, 0.0000, 0.0000],   #  H
        [0.3333, 0.3333, 0.0000],   #  P
        [0.0000, 0.0000, 0.5000],   #  N
        [0.5000, 0.0000, 0.5000],
        [0.3333, 0.3333, 0.5000 ],
        [0.0000, 0.0000, 0.5000 ]] , #  G
                 labels=["G","M","K","G","A", "L", "H"],
                 length=200 )
result_run = wberri.run(system,
            grid=path,
            calculators = calculators,
            parallel=parallel,
            adpt_num_iter=5,
            fout_name='ef',
            restart=False,
            print_Kpoints=False
            )

open("data_Morb","w").write(result_run.results["tabulate"].results["Morb"].data) # To write data in a file since I am running a slurm job

parallel.shutdown()`

But again the same error occurs which is: 
    result_run = wberri.run(system,
  File "/public/home/skp/software/wannier-berri-tab_static/wannierberri/run.py", line 180, in run 
    raise ValueError(f"Calculation along a Path is running, but calculator `{key}` is not compatible with a Path")
ValueError: Calculation along a Path is running, but calculator `Morb` is not compatible with a Path

I would appreciate your help.

**Comment by stepan-tsirkin** [comment]
This cannot be.  This error is raised here:

https://github.com/wannier-berri/wannier-berri/blob/89c53d987aec428a0535d14df1d78f2f68c2a38a/wannierberri/run.py#L175-L180

But the loop is over the dictionary `calculators` which has only one item with key `"tabulate"`  and the complex calculator `TabulatorAll()`, but there is no check of tabulators inside `TabulatorAll` . so where did the key `"Morb"` come from? Are you sure you are running the same code that you are showing here?

Btw ? if you use  [code highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) in your comments, it will be easier to read.

**Comment by shishirkrpandey** [comment]
I reinstalled it, this time with `pip install .` but still some problem with running the calculations, though the code was able to read the input files before giving the error.

Attached is the log file and the slurm output I paste below. 


023-09-12 23:26:10,912 ERROR services.py:1207 -- Failed to start the dashboard 
2023-09-12 23:26:10,915 ERROR services.py:1232 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2023-09-12 23:26:10,915 ERROR services.py:1276 --  
The last 20 lines of /tmp/ray/session_2023-09-12_23-25-21_956967_16082/logs/dashboard.log (it contains the error message from the dashboard): 
2023-09-12 23:25:59,810 INFO head.py:254 -- Starting dashboard metrics server on port 44227
2023-09-12 23:25:59,823 INFO utils.py:112 -- Get all modules by type: DashboardHeadModule

2023-09-12 23:26:12,056 INFO worker.py:1621 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/public/home/aisi/users/skp/work/crte/fm/rlx_u001/wan/reduced_NB=60/morb_contr.py", line 68, in <module>
    result_run = wberri.run(system,
  File "/public/home/aisi/users/yinan/anaconda3/lib/python3.9/site-packages/wannierberri/run.py", line 180, in run 
    raise ValueError(f"Calculation along a Path is running, but calculator `{key}` is not compatible with a Path")
ValueError: Calculation along a Path is running, but calculator `Morb` is not compatible with a Path

Sorry for keep bothering you.

[morb.log](https://github.com/wannier-berri/wannier-berri/files/12589318/morb.log)

**Comment by stepan-tsirkin** [comment]
Could you show the **full** python script that you are running?

Note, that in your log the comment of calculator Morb appears twice. The second - is when it is created in the TabulatorAll, but where does the first come from?  You should not have "Morb" as a standalone calculator.  

Btw, do you really need slurm to run the a path calculation? Usually it is not that many kpoints, it should run quickly on a laptop.  

In PR #276 I pushed a new commit, with a more detailed print of calculators in the beginning of run() . Could you run with this version again and show the logs? First, on a local computer, then on a cluster. 

And to be sure, add a line `print (wberri.__version__)` to your python script.

**Comment by shishirkrpandey** [comment]
Thank you very much for the help. Now it is running fine. 
> You should not have "Morb" as a standalone calculator. 

This was the problem. I removed that standalone line of `Morb` and it worked. I still have a question. In the code below, 

```
path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000 ],   #  G
        [0.5000, 0.0000, 0.0000],   #  H
        [0.3333, 0.3333, 0.0000],   #  P
        [0.0000, 0.0000, 0.5000],   #  N
        [0.5000, 0.0000, 0.5000],
        [0.3333, 0.3333, 0.5000 ],
        [0.0000, 0.0000, 0.5000 ]] , #  G
                 labels=["G","M","K","G","A", "L", "H"],
                 length=200 )
```
I defined length=200 but in the output is # of kpoints are 157 which is also written in the log file 

The set of k points is a Path() with 157 points and labels {0: 'G', 28: 'M', 44: 'K', 80: 'G', 108: 'A', 124: 'L', 156: 'H'}
WARNING : symmetry is not used for a tabulation along path
generating K_list

I was expecting 200 k-points instead of 157, am I wrong ?

Thank a lot again.

**Comment by stepan-tsirkin** [comment]
> I was expecting 200 k-points instead of 157, am I wrong?

It sets the number of k-points along each segment such that the distance between nearest points is approximately $\frac{2\pi}{\rm length}$ , where ${\rm length}$ is in Angstroms.

You can also specify number of points on each segment with `nk` parameter
See https://docs.wannier-berri.org/en/master/docs/grid.html#wannierberri.Path
